import Blurb from "components/Blurb";
import type { GetStaticProps } from "next";
import Head from "next/head";
import { BlurbItemProps } from "types/components";
import { getBlurb } from "utils/contentful";

export interface HomePageProps {
  blurb: BlurbItemProps;
}

const Home = ({ blurb }: HomePageProps) => {
  return (
    <>
      <Head>
        <title>Darren Carlin | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Blurb blurb={blurb} />
    </>
  );
};

export default Home;

export const getStaticProps: GetStaticProps = async () => {
  const blurb = await getBlurb();

  return { props: { blurb } };
};
