import Blurb from "components/Blurb";
import Education from "components/Education";
import Work from "components/Work";
import type { GetStaticProps } from "next";
import Head from "next/head";
import {
  BlurbItemProps,
  EducationItemProps,
  WorkItemProps,
  WorkProps,
} from "types/components";
import { getBlurb, getEducation, getWork } from "utils/contentful";

export interface HomePageProps {
  blurb: BlurbItemProps;
  work: WorkItemProps[];
  education: EducationItemProps[];
}

const Home = ({ blurb, work, education }: HomePageProps) => {
  return (
    <>
      <Head>
        <title>Darren Carlin | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Blurb blurb={blurb} />
      <Work work={work} />
      <Education education={education} />
    </>
  );
};

export default Home;

export const getStaticProps: GetStaticProps = async () => {
  const blurb = await getBlurb();
  const work = await getWork();
  const education = await getEducation();
  return { props: { blurb, work, education } };
};
