import type { GetStaticProps } from "next";
import Head from "next/head";
import { getEducation } from "utils/contentful";
import Education from "components/Education";
import { EducationItemProps } from "types/components";

export interface HomePageProps {
  education: EducationItemProps[];
}

const Home = ({ education }: HomePageProps) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Education education={education} />
    </>
  );
};

export default Home;

export const getStaticProps: GetStaticProps = async () => {
  const education = await getEducation();

  return { props: { education } };
};
